config/routes.rb
Money::Application.routes.draw do
  root 'purchases#index'
  resources :directories do
    collection do
      get 'search'    
      post 'set_parent'
    end
    post :update, on: :member
  end

  resources :reports, only: [:index] do
    collection do
      get 'dirsum' 
      get 'dirchildsum'
    end
  end

  resources :purchases, only: [:index,:create,:update, :destroy]

end

app/models/directory.rb
class Directory < ActiveRecord::Base
  has_and_belongs_to_many :purchases, -> { uniq }
  has_many :children, :class_name => 'Directory', :foreign_key => "parent_id"
  belongs_to :parent, :class_name => 'Directory', :foreign_key => "parent_id"
  has_and_belongs_to_many  :purchases
  before_save :check_parent
  validates :name, uniqueness: true
  def self.find_or_create name
    dir = Directory.find_by_name(name)
    dir = Directory.create(name:name, parent_id: Directory.root.id) unless dir
    return dir
  end

  def self.root
    return Directory.where("parent_id IS NULL").first
  end

  def self.update_full_path options={}
    
    all_need_update_set = if options[:update_all]
      Directory.all.to_set
    else
      Directory.where('datetime(updated_at) > datetime(path_update) OR path_update IS NULL OR full_path IS NULL').to_set
    end

    infinitive_loop = 0    
    while !all_need_update_set.empty?
      current = all_need_update_set.first
      parent = current.parent
      current.full_path = parent.try(:full_path).to_s+parent.try(:id).to_s+'/'
      current.path_update = Time.now.utc.to_s(:db)
      current.save      
      all_need_update_set.delete(current)
      all_need_update_set.merge(current.children.to_a)
    end
  end

  def self_and_all_children
    Directory.update_full_path
    Directory.where("full_path LIKE ? || '%' OR id = ?", self.full_path+self.id.to_s+'/', self.id)
  end  

  def all_purchases
    Purchase.which_belongs_to(self.self_and_all_children.pluck(:id))    
  end

  def check_parent
    if self.parent == nil && self.name != 'root'
      self.parent = Directory.root
    end
  end
end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
  has_and_belongs_to_many :directories, -> { uniq }
  validates :date, presence: true
  validates :cost, presence: true

  def self.which_belongs_to(directories_ids)
    Purchase.all.joins(:directories).where('"directories_purchases"."directory_id" IN (?)', directories_ids )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/directories_controller.rb
class DirectoriesController < ApplicationController
  before_action :set_directory, only: [:show, :edit, :update, :destroy]

  def index
    @directories = Directory.all
  end

  def show
  end

  def new
    @directory = Directory.new
  end


  def edit
  end

  def create    
    @directory = Directory.new(directory_params)
    if @directory.save
      render :json => {status: 'ok', dir: @directory}.to_json  
    else
      render :json => {status: 'fail', errors: @directory.errors}.to_json  
    end
    
  end


  def update
    respond_to do |format|
      if directory_params[:name].empty?
        parent = @directory.parent
        parent.purchases<<@directory.purchases
        parent.children<<@directory.children
        @directory.destroy
      else
        if @directory.update(directory_params)
          format.html { redirect_to @directory, notice: 'Directory was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @directory.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  def destroy
    @directory.destroy
    respond_to do |format|
      format.html { redirect_to directories_url }
      format.json { head :no_content }
    end
  end

  def search    
    res = Directory.where('name like :q',q:'%'+params[:q].to_s+'%')
    # check if :q already in respond_to
    unless params[:exist_only]=="true" || res.map(&:name).include?(params[:q])
      res<<Directory.new(name:params[:q])
    end
    json_res = res.map{|dir| dir.name}.to_json
    render :json => json_res
  end

  def set_parent 
    child = Directory.find_by_name(params[:child_name])
    parent = params[:parent_name]!='null' ? Directory.find_by_name(params[:parent_name]) : Directory.root
    if child&&parent
      child.parent = parent              
      render json: child.save
    else
      render json: 'Not Found'
    end
  end

  private
    def set_directory
      @directory = Directory.find(params[:id])
    end

    def directory_params
      params.require(:directory).permit(:name, :directories_purchases_id)
    end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :set_purchase, only: [:show, :edit, :update, :destroy]

  # GET /purchases
  # GET /purchases.json
  def index    
    @date = params[:date].try(:to_date) || Date.today
    @purchases = Purchase.where("date = ?",@date).includes(:directories)
    @new_purchase = Purchase.new(date: @date)
  end

  # GET /purchases/1
  # GET /purchases/1.json
  def show
  end

  # GET /purchases/new
  def new
    @purchase = Purchase.new
  end

  # GET /purchases/1/edit
  def edit
  end

  # POST /purchases
  # POST /purchases.json
  def create    
    @purchase = Purchase.new(purchase_params)    
    if !params[:purchase][:directories].empty? && @purchase.save
      # create dir assosiations
      params[:purchase][:directories].split(',').each do |name|
        @purchase.directories<<Directory.find_or_create(name);
      end      
      render :json => {status: 'created', edit_destroy_link: purchase_path(@purchase)}.to_json
    else
      render :json => {status: 'fail'}.to_json
    end    
  end

  # PATCH/PUT /purchases/1
  # PATCH/PUT /purchases/1.json
  def update
    if !params[:purchase][:directories].empty? && @purchase.update(purchase_params)
      # create dir assosiations
      @purchase.directories.delete_all
      params[:purchase][:directories].split(',').each do |name|
        @purchase.directories<<Directory.find_or_create(name);
      end
      render :json => {status: 'updated'}.to_json
    else
      render :json => {status: 'fail'}.to_json
    end
    
  end

  # DELETE /purchases/1
  # DELETE /purchases/1.json
  def destroy    
    if @purchase.destroy
      render json: 'Destroyed'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_purchase
      @purchase = Purchase.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def purchase_params
      pur_params = params.require(:purchase).permit(:cost, :name, :directories_purchases_id,:date)
      pur_params[:date] = pur_params[:date].to_date
      return pur_params
    end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
    
  end

  def dirsum
    dirs = ActiveSupport::JSON.decode( params[:directories])
    dir_names = dirs.map{|hash| hash["text"]}
    top_dir =  Directory.where("name in (?)",dir_names);
    dir_ids = top_dir.map{|e| e.self_and_all_children.pluck(:id)}.flatten.uniq    
    purs =  Purchase.which_belongs_to(dir_ids).group(:date).sum(:cost)
    return_val = purs.map {|k, v| [k.to_datetime.to_i*1000, v] }    
    render json: return_val.to_json
  end

  def dirchildsum
    dir = Directory.find_by_name(params[:directory])
    rez = []
    childs = dir.children
    childs.each{|child| rez<<{label:child.name, data: child.all_purchases.sum(:cost)}}
    rez<<{label: "Без категории", data: dir.purchases.sum(:cost)}
    render json: rez.to_json
  end

end

app/helpers/directories_helper.rb
module DirectoriesHelper  
  def list_struct_of dir, &blk
    ret = content_tag :ul, class: 'folder'  do      
      dir.children.collect do |child|
        str = blk.call(child)
        li = content_tag :li, class: 'folder' do
          content_tag(:span, str) + list_struct_of(child,&blk)
        end
        concat li
      end      
    end
  end  
end
# def list_struct_of dir
#     ret = content_tag :ul, class: 'folder'  do      
#       dir.children.collect do |child|
#         li = content_tag :li, class: 'folder' do
#           content_tag(:span, (yield child)) + list_struct_of(child)
#         end
#         concat li
#       end      
#     end
#   end

app/helpers/report_helper.rb
module ReportHelper
end

app/views/directories/index.html.haml
.add
  = form_for Directory.new(parent_id: Directory.root.id), remote: true, html: {class: 'add_dir'} do |f|
    = f.text_field :name
    = f.hidden_field :parent_id
    = f.submit '+'
.tree
  = list_struct_of(Directory.first) do |dir|
    - name =  content_tag :span, dir.name 
    - edit = link_to '', directory_path(dir), class: 'nodisp', style: 'border:0'
    - name+edit
    

.nodisp
  = link_to 'Change parent catalog', set_parent_directories_path(child_name:'_child_',parent_name:'_parent_'), class: 'change_dir'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      Money
  =stylesheet_link_tag "application"  
  = csrf_meta_tags

%body.app
  %nav.navbar.navbar-default.main{role:'navigation'}
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li
          =link_to 'Добавление', purchases_path
        %li
          =link_to 'Дерево каталогов', directories_path
        %li
          =link_to 'Отчетность', reports_path
  .wrapper
    = yield
  
=javascript_include_tag "application"

app/views/purchases/_form.html.haml
.pur_form.row
  - p = locals[:p];
  = form_for(p, remote:true, disable_with: "Submitting...") do |f|    
    .col-xs-1.pur_destroy
      - path = p.new_record? ? '#' : purchase_path(p)
      =link_to 'X', path, method: 'delete', remote: true, class: ('nodisp' if p.new_record?)
    .col-xs-6.pur_dir.cell   
      = text_field_tag 'purchase[directories]', p.directories.map(&:name).join(", "), class: 'main_input'
    .col-xs-1.pur_cost.cell      
      = f.text_field :cost, :value => "%0.2f" % (p.cost || 0), class: 'main_input'
    .pur_date.cell.modal.nodisp
      = f.text_field :date
    .col-xs-2.pur_name.cell
      = f.text_field :name, class: 'main_input'
    .col-xs-1.pur_date_change.cell
      = link_to "#",'#',class: 'change_date'
    .col-xs-1.status.cell
      .error.nodisp
        Error!
      .ok.nodisp
        Ок!
      .wait.nodisp
        Send...
      .change.nodisp
        =link_to  'Unsafed','#'

app/views/purchases/_index.html.haml
.mini_navigate
  .date
    = link_to '<<', purchases_path(date:@date.prev_day()), remote: true, class: 'prev'
    = text_field_tag 'purchase[date]', @date.strftime("%d-%m-%Y"), url: purchases_path(date:'')
    = link_to '>>', purchases_path(date:@date.next_day()), remote: true, class: 'next'
    .nodisp
      = link_to 'Go to typed date', purchases_path(date:''), remote: true, class: 'go'

.forms
  - @purchases.each do |p|  
    =render 'form', locals:{p:p}
  %br.separator
  = render 'form', locals:{p:@new_purchase}

app/views/purchases/index.html.haml
.ajax-wait-msg.nodisp
  Загрузка...
.ajax-reload
  =render 'index'

app/views/purchases/index.js.erb
$(".ajax-reload").html('<%= j(render "index") %>');
document.pur_script();
$(".ajax-wait-msg").hide();

app/views/reports/index.html.haml
.row.dates
  %center    
    .date-buttons
      = button_tag 'Last month', class: 'last_month'
      = button_tag 'Last week', class: 'last_week'
    .date-field
      = text_field_tag :from, nil,placeholder:'From (10.10.2010)'
      = text_field_tag  :to, nil, placeholder:'To (10.10.2013)'
.row.graph1
  .col-xs-8
    #plot1
    #overview1
  .col-xs-4
    = text_field_tag :directories, Directory.root.name
.row.graph2
  .col-xs-8
    #plot2    
  .col-xs-4
    = text_field_tag :directory, Directory.root.name